### PR TITLE
fix #58 - Call to a member function getCallable() on bool.

### LINKED ISSUE #58: [Bug] Latest PR #52 introduced side effect Call to a member function getCallable() on bool
**Describe the bug**
When checking customer profil in admin area got the following error:
Call to a member function getCallable() on bool.
Faulty code:
`        if ($function !== null && is_callable($function->getCallable())) {` in GdprExtension.php

This extension is directly related to sylius_plus, but in vanilla sylius, this twig extension does not exists.

**To Reproduce**
Go to /admin/customers/xxxxx

**Expected behavior**
No error

**Screenshots**
Error 500

**Additional context**

### PR DESCRIPTION
**Pull request by oallain**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?   | no
| Fixed issue | #58

### CODE REVIEW

File: src/Twig/GdprExtension.php [hunk 1]
```diff
@@ -21,7 +21,7 @@ public function hasPermission(Environment $env, string $permission): bool
     {
         $function = $env->getFunction('sylius_plus_rbac_has_permission');
 
-        if ($function !== null && is_callable($function->getCallable())) {
+        if (is_object($function) && is_callable($function->getCallable())) {
```
Comment (benjamin-volle) [inline src/Twig/GdprExtension.php]: In my opinion it's pretty weird to check if a variable called "function" is an object or not

Comment (oallain) [reply src/Twig/GdprExtension.php]: The method signature has changed between Twig v2 and Twig v3.

Twig v2
```php
    /**
     * @return TwigFunction|false
     */
    public function getFunction($name)
```

In Twig v3
```php
    public function getFunction(string $name): ?TwigFunction
```

So check only with `null` is not enough.

Comment (Jibbarth) [inline src/Twig/GdprExtension.php]: i would suggest this instead
```suggestion
        if ($function instanceof TwigFunction && is_callable($function->getCallable())) {
```

**Review by Jibbarth — APPROVED** [review]
